# MOTD. Uncomment if you want an example
motd:
  #- "Welcome ${username}!"
  #- "You are currently in ${world}."
  #- "Players online: ${onlineCount}/${totalSlots}"
  #- "${hour}:${minute}:${second} - ${day}.${month}.${year} - ${timezone}"